import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/common/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full antialiased" suppressHydrationWarning>
      <body className="group min-h-full flex flex-col selection:bg-[#9FD923]/90 relative overflow-x-hidden">

        {/* Background Gradient Layer */}
        <div className="fixed inset-0 bg-linear-to-b from-[#CAFD00]/20 via-white/80 to-white -z-10" />

        <Header />
        <main className="flex-1 pt-28 relative">{children}</main>
      </body>
    </html>
  );
}
